# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_USB_DEVICE_PID=0x6160
CONFIG_BT_DIS_PNP_PID=0x6160

CONFIG_NICE_VIEW_HID_LAYOUTS="EN,RU"
CONFIG_NICE_VIEW_HID_TWO_PROFILES=y
# CONFIG_NICE_VIEW_HID_INVERTED=y
