# configuration for https://github.com/caksoylar/keymap-drawer
parse_config:
  raw_binding_map:
    '&sys_reset': Reset
    '&bootloader': Boot
    '&caps_word': Caps Word

    '&m_arrow': =>
    '&m_email': email

    '&kp RA(A)': Ą
    '&kp RA(E)': Ę
    '&kp RA(S)': Ś
    '&kp RA(Z)': Ż
    '&kp RA(X)': Ź
    '&kp RA(C)': Ć
    '&kp RA(U)': €
    '&kp RA(O)': Ó
    '&kp RA(L)': Ł
    '&kp RA(N)': Ń
    '&kp LC(C)': Copy
    '&kp LC(V)': Paste
    '&kp LA(UP)': Alt↑
    '&kp LA(DOWN)': Alt↓

    '&out OUT_USB': Out USB
    '&out OUT_BLE': Out BLE
    '&out OUT_TOG': Out TOG
    
    '&ext_power EP_OFF': n!v off
    '&ext_power EP_ON': n!v on

    '&bt BT_SEL 0': BT 1
    '&bt BT_SEL 1': BT 2
    '&bt BT_SEL 2': BT 3
    '&bt BT_SEL 3': BT 4
    '&bt BT_SEL 4': BT 5
    '&bt BT_CLR': BT clear

  zmk_combos:
    combo_caps_word: {align: top}

  zmk_keycode_map:
    # custom mappings
    C_VOL_UP: Vol Up
    C_VOL_DN: Vol Down
    C_AL_CALC: Calc
    C_PP: Play Pause

    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: AltGr
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift
    ESC: Esc
    SPACE: ␣
    BSPC: ⌫
    RET: ⏎
    ENTER: ⏎
    TAB: ↹
    DEL: ⌦

    PG_UP: Page Up
    PG_DN: Page Down
    INS: Insert
    HOME: Home
    END: End
    CAPS: Caps Lock
    PSCRN: Print Scrn
    PAUSE_BREAK: Pause Break

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    C_PP: ⏯
    C_NEXT: ⏭️
    C_PREV: ⏮️

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _